#!/usr/bin/env python3
"""Build the .osbui UI-asset bundle for an injected fighter.

Assets produced (matching Mario's sprite layouts exactly):
  - CSS portrait: 48x43 RGBA32 canvas (drawn 45x43) — generated art + name
                  text, encoded as three strips overlapping by one row
                  (see PORTRAIT_STRIPS)
  - CSS name:     48x16 IA8 (drawn 47x16) — composed from the game's own
                  letter sprites (web-prototype/visual/assets/ui_refs/glyph_*.png, extracted from the
                  12 roster name sprites; Q is synthesized)
  - stock icon:   16x10 CI4 + 16-color RGBA5551 palette (drawn 8x10)
  - emblem:       48x48 coverage canvas (series-emblem glyph; the engine
                  re-encodes to each target sprite's I/IA geometry) —
                  appended only when --emblem is given. Built as a STENCIL
                  (emblem_stencil.py), not the art's alpha: the engine
                  draws the canvas as one flat tint, so a solid object's
                  silhouette lands as a blob. See
                  web-prototype/visual/assets/ui_refs/emblem_ref.png.

The portrait art comes from an image file (--art), typically generated by
gen.py with the roster tiles as style references. All texel data is
pre-encoded to the DRAM state the engine memcpy's (sprite_codec.encode).

Usage:
  gen_ui_assets.py --art queen_portrait.png --name QUEEN out.osbui [--preview p.png]
"""
import argparse
import glob
import os
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
try:
    from . import emblem_stencil
    from .pixel_font import render_caption, render_panel_name
    from .sprite_codec import encode, u32rev
except ImportError:  # direct execution: python3 pipeline/gen_ui_assets.py
    import emblem_stencil
    from pixel_font import render_caption, render_panel_name
    from sprite_codec import encode, u32rev

# (width, height, source row) per strip. spDraw advances the screen y by
# bmheight (20) per strip but each strip stores/draws bmHreal (21) rows, so
# consecutive strips OVERLAP by one row on screen: strip N+1's first row
# repeats strip N's last drawn row (vanilla data duplicates those rows
# byte-for-byte). Content canvas is therefore 43 rows, not 21+21+3=45 —
# disjoint strips displace everything below row 20 and draw a seam across
# the middle of the tile.
PORTRAIT_STRIPS = [(48, 21, 0), (48, 21, 20), (48, 3, 40)]
PORTRAIT_W, PORTRAIT_H = 48, 43
PORTRAIT_DRAW_W, PORTRAIT_DRAW_H = 45, 43
NAME_W, NAME_H, NAME_DRAW_W = 48, 16, 47
STOCK_W, STOCK_H = 16, 10
VS_W, VS_H, VS_DRAW_W = 48, 12, 35  # 1P VS-splash name, I4


def load_atlas(prefix="glyph"):
    atlas = {}
    refs = os.path.join(HERE, "web-prototype", "visual", "assets", "ui_refs")
    for p in glob.glob(os.path.join(refs, prefix + "_*.png")):
        atlas[chr(int(os.path.basename(p)[len(prefix) + 1:-4]))] = Image.open(p).convert("RGBA")
    return atlas


def _compose(atlas, text, pad, height):
    gl = [atlas[c] for c in text if c in atlas]
    w = sum(g.width for g in gl) + pad * (len(gl) - 1)
    im = Image.new("RGBA", (w, height), (0, 0, 0, 0))
    x = 0
    for g in gl:
        im.alpha_composite(g, (x, 0))
        x += g.width + pad
    return im


def _trim_x(g):
    xs = [x for x in range(g.width) for y in range(g.height) if g.getpixel((x, y))[3] > 100]
    return g.crop((min(xs), 0, max(xs) + 1, g.height)) if xs else g


def _outline(im, color=(52, 32, 22, 255)):
    """1px dark border around opaque pixels, like the baked tile captions."""
    out = Image.new("RGBA", (im.width + 2, im.height + 2), (0, 0, 0, 0))
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            if dx or dy:
                mask = im.getchannel("A").point(lambda a: 255 if a > 100 else 0)
                plate = Image.new("RGBA", im.size, color)
                out.paste(plate, (1 + dx, 1 + dy), mask)
    out.alpha_composite(im, (1, 1))
    return out


def compose_tile_text(text):
    """Hand-authored pixel font (pixel_font.py), vanilla caption style —
    fixed cap height and stroke weight, fit by tracking, never resampled.
    (The old path composited auto-sliced screenshot glyphs and Lanczos-
    squashed overflow, which dropped stroke columns and varied the size.)"""
    return render_caption(text, PORTRAIT_DRAW_W - 1)


def compose_name(text, max_width=None):
    """Bold panel name from the hand-authored pixel font (pixel_font.py) —
    fixed cap height, never resampled (the old auto-sliced atlas produced
    the WEJR-DAI style garbage on synthesized letters)."""
    # the engine grows the target name sprite up to 64 texels (vanilla
    # sizes them per name, FOX 32 .. DK 72), so the full canvas is usable
    return render_panel_name(text, max_width or 58)


def key_bg(im, thresh=60):
    bg = im.getpixel((2, 2))
    px = im.load()
    for y in range(im.height):
        for x in range(im.width):
            p = px[x, y]
            if abs(p[0] - bg[0]) + abs(p[1] - bg[1]) + abs(p[2] - bg[2]) <= thresh:
                px[x, y] = (p[0], p[1], p[2], 0)
    return im


def head_crop(tpose_path):
    """bbox the figure on its flat background, take the head slice, key the bg."""
    im = Image.open(tpose_path).convert("RGBA")
    bg = im.getpixel((2, 2))
    W, H = im.size
    px = im.load()
    xs, ys = [], []
    for y in range(0, H, 2):
        for x in range(0, W, 2):
            p = px[x, y]
            if abs(p[0] - bg[0]) + abs(p[1] - bg[1]) + abs(p[2] - bg[2]) > 60:
                xs.append(x)
                ys.append(y)
    x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
    side = int((y1 - y0) * 0.30)
    cx = (x0 + x1) // 2
    return key_bg(im.crop((cx - side // 2, y0, cx + side // 2, y0 + side)))


def rgba5551(r, g, b, a=255):
    return ((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | (1 if a >= 128 else 0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out")
    ap.add_argument("--art", required=True, help="portrait art image (any size, squarish)")
    ap.add_argument("--tpose", default=None, help="T-pose render on flat bg; fallback stock-icon source")
    ap.add_argument("--stock-art", default=None,
                    help="generated chibi head icon on a solid background (preferred stock source)")
    ap.add_argument("--emblem", default=None,
                    help="series-emblem glyph art on a solid background; becomes the CSS "
                         "card watermark AND the stock icon (overrides --stock-art)")
    ap.add_argument("--emblem-mask", default=None,
                    help="pre-made emblem stencil (ink = opaque/white); skips "
                         "the automatic stencil derived from --emblem")
    ap.add_argument("--name", required=True)
    ap.add_argument("--preview", default=None)
    a = ap.parse_args()
    name = a.name.upper()[:10]

    art = Image.open(a.art).convert("RGBA")

    # ---- portrait ----
    port = Image.new("RGBA", (PORTRAIT_W, PORTRAIT_H), (0, 0, 0, 255))
    port.paste(art.resize((PORTRAIT_DRAW_W, PORTRAIT_DRAW_H), Image.LANCZOS), (0, 0))
    txt = compose_tile_text(name)
    bbox = txt.getbbox()  # crop empty margins so placement is exact
    txt = txt.crop(bbox)
    # vanilla captions: outline row at y=2, face rows 3..9, starting x~4
    port.alpha_composite(txt, (3, 2))
    logical = bytearray()
    for y in range(PORTRAIT_H):
        for x in range(PORTRAIT_W):
            p = port.getpixel((x, y))
            logical += bytes((p[0], p[1], p[2], 255))
    row = PORTRAIT_W * 4
    portrait_enc = b""
    for w, h, y0 in PORTRAIT_STRIPS:
        portrait_enc += encode(bytes(logical[y0 * row:(y0 + h) * row]), w, h, 32)

    # ---- name: raw IA8 canvas (64x16) — the engine re-encodes into the
    # target fighter's own sprite geometry (40/48/64 wide varies) ----
    nm = Image.new("RGBA", (64, NAME_H), (0, 0, 0, 0))
    ptxt = compose_name(name)
    pb = ptxt.getbbox()
    # vanilla panel names are left-aligned, face starting ~col 5 / row 1
    nm.alpha_composite(ptxt.crop(pb), (3, 1))
    name_enc = bytes(((nm.getpixel((x, y))[0] >> 4) << 4) | (nm.getpixel((x, y))[3] >> 4)
                     for y in range(NAME_H) for x in range(64))

    # ---- emblem glyph (shared by stock icon + CSS watermark canvas) ----
    emb = None
    if a.emblem:
        emb = Image.open(a.emblem).convert("RGBA")
        if max(emb.size) > 256:
            emb = emb.resize((256, 256 * emb.height // emb.width), Image.LANCZOS)
        emb = key_bg(emb, thresh=90)
        eb = emb.getbbox()
        if eb:
            emb = emb.crop(eb)

    # ---- stock icon (drawn area = left 8x10 of the 16x10 bitmap) ----
    if emb is not None:
        # the emblem IS the stock icon, like the vanilla series emblems
        scale = min(8 / emb.width, 10 / emb.height)
        head = emb.resize((max(1, round(emb.width * scale)),
                           max(1, round(emb.height * scale))), Image.LANCZOS)
        scale = None
    elif a.stock_art:
        # Generated chibi head (1024px "fake pixel art"). Box-average down
        # to the art's ~16x16 logical grid first — crisp logical pixels,
        # no sampling lottery — then key the bg, strip the drawn outline
        # (it downsamples to speckle at 8x10; vanilla icons have no ring),
        # and reduce to the drawn area.
        head = Image.open(a.stock_art).convert("RGBA").resize((16, 16), Image.BOX)
        head = key_bg(head, thresh=110)
        px = head.load()
        for y in range(head.height):
            for x in range(head.width):
                r, g, b, al = px[x, y]
                if al and (r + g + b) < 140:
                    px[x, y] = (r, g, b, 0)
        hb = head.getbbox()
        if hb:
            head = head.crop(hb)
        scale = min(8 / head.width, 10 / head.height)
        head = head.resize((max(1, round(head.width * scale)),
                            max(1, round(head.height * scale))), Image.NEAREST)
        scale = None
    else:
        head = head_crop(a.tpose)
        hb = head.getbbox()
        if hb:
            head = head.crop(hb)
        scale = min(6 / head.width, 8 / head.height)
    if scale is not None:
        head = head.resize((max(1, round(head.width * scale)), max(1, round(head.height * scale))),
                           Image.LANCZOS)
    st = Image.new("RGBA", (STOCK_W, STOCK_H), (0, 0, 0, 0))
    st.alpha_composite(head, ((8 - head.width) // 2, (10 - head.height) // 2))
    if not a.stock_art and emb is None:
        # tpose fallback has no baked outline — add one
        mask = st.getchannel("A").point(lambda v: 255 if v > 100 else 0)
        out = Image.new("RGBA", (STOCK_W, STOCK_H), (0, 0, 0, 0))
        plate = Image.new("RGBA", (STOCK_W, STOCK_H), (25, 15, 15, 255))
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                if dx or dy:
                    out.paste(plate, (dx, dy), mask)
        out.alpha_composite(st, (0, 0))
        st = out
    q = st.convert("RGB").quantize(colors=15, method=Image.MEDIANCUT)
    qpal = q.getpalette()[:45]
    qpal += [0] * (45 - len(qpal))
    pal = [0] + [rgba5551(qpal[i * 3], qpal[i * 3 + 1], qpal[i * 3 + 2]) for i in range(15)]
    idx = [0 if st.getpixel((x, y))[3] < 128 else q.getpixel((x, y)) + 1
           for y in range(STOCK_H) for x in range(STOCK_W)]
    ci4 = bytes((idx[i] << 4) | idx[i + 1] for i in range(0, len(idx), 2))
    stock_enc = encode(ci4, STOCK_W, STOCK_H, 4)
    pal_enc = u32rev(b"".join(bytes(((v >> 8) & 0xFF, v & 0xFF)) for v in pal))

    # ---- VS-splash name: raw intensity canvas (64x12), engine packs to
    # the target's I4 geometry ----
    vtxt = compose_name(name, VS_DRAW_W)   # fit by tracking/condense, no resize
    vtxt = vtxt.crop(vtxt.getbbox())
    vim = Image.new("RGBA", (64, VS_H), (0, 0, 0, 0))
    vim.alpha_composite(vtxt, (0, max(0, (VS_H - vtxt.height) // 2)))
    vs_enc = bytes((lambda p: (p[0] + p[1] + p[2]) // 3 * p[3] // 255)(vim.getpixel((x, y)))
                   for y in range(VS_H) for x in range(64))

    # ---- emblem canvas: 48x48 pure-coverage bytes; the engine fits the
    # content bbox into each target emblem sprite (aspect kept, centered)
    # and encodes per that sprite's I4/IA4/I8/IA8 format ----
    emb_enc = b""
    emb_stats = ""
    if a.emblem_mask:
        m = np.asarray(Image.open(a.emblem_mask).convert("LA"))
        m = (m[..., 0] > 127) & (m[..., 1] > 127)
        emb_enc = emblem_stencil.canvas(m, 48).tobytes()
        emb_stats = " (mask supplied)"
    elif emb is not None:
        m, sil = emblem_stencil.stencil(a.emblem)
        if m is None:
            print(f"WARNING: {a.emblem} keyed to nothing — emblem canvas skipped")
        else:
            escore = emblem_stencil.score(m, sil)
            emb_enc = emblem_stencil.canvas(m, 48).tobytes()
            emb_stats = (f" (cut {escore['cut_frac']:.0%} in {escore['cuts']} holes"
                         + (", BLOBBY" if escore["blobby"] else "") + ")")

    with open(a.out, "wb") as f:
        f.write(b"OSBV" + portrait_enc + name_enc + stock_enc + pal_enc + vs_enc + emb_enc)
    print(f"{a.out}: portrait {len(portrait_enc)}B name {len(name_enc)}B "
          f"stock {len(stock_enc)}B pal {len(pal_enc)}B vs {len(vs_enc)}B "
          f"emblem {len(emb_enc)}B{emb_stats}")

    if a.preview:
        pv = Image.new("RGBA", (48 * 4 + 16, 43 * 4 + 16 * 4 + 10 * 8 + 36), (30, 30, 30, 255))
        pv.paste(port.resize((48 * 4, 43 * 4), Image.NEAREST), (8, 8))
        pv.paste(nm.resize((48 * 4, 16 * 4), Image.NEAREST), (8, 43 * 4 + 16))
        pv.paste(st.resize((16 * 8, 10 * 8), Image.NEAREST), (8, 43 * 4 + 16 * 4 + 26))
        pv.save(a.preview)


if __name__ == "__main__":
    main()
